import asyncio
import os
import json
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Ensure we have the required keys
if not os.getenv("GEMINI_API_KEY"):
    print("❌ Error: GEMINI_API_KEY not found in .env")
    exit(1)

# Import the parser
from parsing.parsers import parse_document
from chunking.strategies import chunk_markdown, chunk_figures

async def main():
    print("🚀 Starting Multimodal Pipeline Test...")
    
    # 1. Look for a test file
    test_file_path = Path("test_document.pdf")
    if not test_file_path.exists():
        print(f"❌ Error: Please put a PDF file named 'test_document.pdf' in {os.getcwd()}")
        print("   Make sure it has at least one image or chart to test the multimodal extraction!")
        return

    # 2. Read the file
    print(f"\n📂 Reading {test_file_path}...")
    with open(test_file_path, "rb") as f:
        file_bytes = f.read()

    # 3. Run the parser (Docling + Gemini 3.5 Flash-Lite)
    print("\n🧠 Running Docling Parser & Gemini Vision (This might take a minute)...")
    try:
        result = await parse_document(file_bytes, test_file_path.name)
    except Exception as e:
        print(f"❌ Parsing failed: {e}")
        return

    # 4. Display Results
    print("\n✅ Parsing Complete!")
    print(f"   - Markdown extracted: {len(result.markdown_text)} characters")
    print(f"   - Images extracted: {len(result.extracted_images)}")
    print(f"   - Captions generated: {len(result.figure_captions)}")

    if result.figure_captions:
        print("\n🖼️ First Image Caption generated by Gemini:")
        print("-" * 50)
        print(result.figure_captions[0].caption)
        print("-" * 50)

    # 5. Run Chunking
    print("\n✂️ Chunking the results...")
    import uuid
    doc_id = uuid.uuid4()
    
    text_chunks = chunk_markdown(result.markdown_text, doc_id, "pdf")
    figure_chunks = chunk_figures(result.figure_captions, doc_id, "pdf", len(text_chunks))
    
    print(f"   - Generated {len(text_chunks)} text chunks")
    print(f"   - Generated {len(figure_chunks)} figure chunks")

    # Optional: We stop before hitting Pinecone so you don't mess up your DB
    print("\n✅ Test successful! The pipeline works perfectly.")
    print("   Note: We skipped the Pinecone embedding step to avoid cluttering your database during testing.")

if __name__ == "__main__":
    asyncio.run(main())
