#!/usr/bin/env bash
# Provision a fresh Ubuntu/Debian VPS and bring OmniMind up on it.
#
#   ./deploy.sh <host> <domain> <tls-email> [ssh-user]
#
# Idempotent: safe to re-run to deploy an update. Everything it needs comes from
# the repo plus the local .env, so it works on any provider that gives you a VPS
# and an SSH key — Hostinger, Hetzner, DigitalOcean, EC2, anything.
#
# The image is built ON the server rather than pushed from here: it is ~3.7GB, and
# building from the public repo avoids both a very slow upload and the need to
# authenticate a container registry.

set -euo pipefail

HOST="${1:?usage: deploy.sh <host> <domain> <tls-email> [ssh-user]}"
DOMAIN="${2:?usage: deploy.sh <host> <domain> <tls-email> [ssh-user]}"
TLS_EMAIL="${3:?usage: deploy.sh <host> <domain> <tls-email> [ssh-user]}"
SSH_USER="${4:-root}"

REPO_URL="https://github.com/sumansatyaranjanpanda/OmniMind.git"
APP_DIR="/opt/omnimind"
LOCAL_ENV="$(cd "$(dirname "$0")/.." && pwd)/.env"
SSH="ssh -o StrictHostKeyChecking=accept-new ${SSH_USER}@${HOST}"

say() { printf "\n\033[1;36m==> %s\033[0m\n" "$*"; }

[ -f "$LOCAL_ENV" ] || { echo "missing $LOCAL_ENV — API keys are read from it"; exit 1; }

say "Checking connectivity to ${SSH_USER}@${HOST}"
$SSH "echo connected as \$(whoami) on \$(. /etc/os-release && echo \$PRETTY_NAME)"

say "Installing Docker if absent"
$SSH 'command -v docker >/dev/null 2>&1 || (curl -fsSL https://get.docker.com | sh)'
$SSH 'docker compose version >/dev/null 2>&1 || apt-get update -qq && apt-get install -y -qq docker-compose-plugin'

say "Configuring firewall (22, 80, 443)"
# `|| true` because a VPS image without ufw is fine — the provider's own firewall
# is then the control, and failing the deploy over it would be wrong.
$SSH 'command -v ufw >/dev/null 2>&1 && { ufw allow 22/tcp; ufw allow 80/tcp; ufw allow 443/tcp; ufw --force enable; } || true'

say "Fetching source into ${APP_DIR}"
$SSH "if [ -d ${APP_DIR}/.git ]; then cd ${APP_DIR} && git fetch --quiet origin && git reset --hard origin/main; else git clone --quiet ${REPO_URL} ${APP_DIR}; fi"

say "Building production .env"
# Secrets are generated once and then reused, so re-running this script does not
# invalidate every issued JWT or orphan the Postgres volume behind a new password.
JWT_SECRET=$($SSH "grep -h '^JWT_SECRET_KEY=' ${APP_DIR}/deploy/.env 2>/dev/null | cut -d= -f2-" || true)
PG_PASSWORD=$($SSH "grep -h '^POSTGRES_PASSWORD=' ${APP_DIR}/deploy/.env 2>/dev/null | cut -d= -f2-" || true)
[ -n "${JWT_SECRET}" ]  || JWT_SECRET=$(python -c "import secrets; print(secrets.token_urlsafe(48))")
[ -n "${PG_PASSWORD}" ] || PG_PASSWORD=$(python -c "import secrets; print(secrets.token_urlsafe(24))")

TMP_ENV=$(mktemp)
trap 'rm -f "$TMP_ENV"' EXIT
{
    echo "# Generated by deploy/deploy.sh — do not commit."
    echo "DOMAIN=${DOMAIN}"
    echo "TLS_EMAIL=${TLS_EMAIL}"
    echo "JWT_SECRET_KEY=${JWT_SECRET}"
    echo "POSTGRES_PASSWORD=${PG_PASSWORD}"
    echo "ENVIRONMENT=production"
    # Serving unauthenticated requests as the demo user would collapse tenant
    # isolation, since tenant_id is derived from the resolved user.
    echo "ALLOW_DEMO_USER_FALLBACK=false"
    # Only the third-party API keys are carried over from the local .env. Local
    # infrastructure URLs are deliberately excluded — compose supplies those, and
    # a stray localhost DATABASE_URL here would point the app at nothing.
    grep -E '^(GEMINI_|PINECONE_|COHERE_|TAVILY_|OPENAI_|LANGFUSE_|VOICE_)' "$LOCAL_ENV" || true
} > "$TMP_ENV"

scp -q -o StrictHostKeyChecking=accept-new "$TMP_ENV" "${SSH_USER}@${HOST}:${APP_DIR}/deploy/.env"
$SSH "chmod 600 ${APP_DIR}/deploy/.env"

say "Building image on the server (first run takes ~15-25 min)"
$SSH "cd ${APP_DIR} && docker build -t omnimind:prod ."

say "Starting the stack"
$SSH "cd ${APP_DIR}/deploy && docker compose -f docker-compose.prod.yml up -d --remove-orphans"

say "Waiting for the API to report healthy"
$SSH "for i in \$(seq 1 60); do
        s=\$(docker inspect -f '{{.State.Health.Status}}' omnimind-api-1 2>/dev/null || echo starting)
        [ \"\$s\" = healthy ] && { echo 'api healthy'; exit 0; }
        sleep 10
      done
      echo 'api did not become healthy; recent logs:'
      docker compose -f ${APP_DIR}/deploy/docker-compose.prod.yml logs --tail 40 api
      exit 1"

say "Deployed — https://${DOMAIN}"
echo "DNS must point ${DOMAIN} at ${HOST} for TLS issuance to succeed."
